### ISSUE TITLE
Error : Hot reload

### ISSUE THREAD

**Issue by FlashPapa** [inertiajs/pingcrm-svelte#13]
Hi,
I have this bug when i reload page with 'hot'  (npm run hot)
Thanks

<img width="952" alt="Capture d’écran 2021-11-27 à 17 44 33" src="https://user-images.githubusercontent.com/2919658/143689802-3db25415-6f33-4c9c-aa3e-ac2a5aba45db.png">

**Comment by pedroborges** [comment]
The project has been update to use Vite and hot reloading works now.
