### ISSUE TITLE
Bug: link doesn't set active class when clicked

### ISSUE THREAD

**Issue by kresnasatya** [inertiajs/pingcrm-svelte#3]
Hi @pedroborges, I just try this demo project and when I click a link (e.g. Organizations) it doesn't show active class and link shows active class when I refresh the page as demonstrated video below.

https://user-images.githubusercontent.com/11099186/103476675-d7084580-4df2-11eb-9f2c-f5db777b16e1.mov

**Comment by vladrusu** [comment]
+1
Interesting, in mobile layout, it sets active class (in hamburger menu).

**Comment by kresnasatya** [comment]
Yes, you're right in mobile layout it sets active class but in desktop layout it doesn't.

**Comment by vladrusu** [comment]
I finally managed to fix it.

(Updated) **MainMenu.svelte**
```
<script>
  import MainMenuItem from '@/Shared/MainMenuItem.svelte'
</script>

<div {...$$restProps}>
    <MainMenuItem text="Dashboard" link="dashboard" icon="dashboard"/>
    <MainMenuItem text="Organizations" link="organizations" icon="office"/>
    <MainMenuItem text="Contacts" link="contacts" icon="users"/>
    <MainMenuItem text="Reports" link="reports" icon="printer"/>
</div>
```

(New) **MainMenuItem.svelte**
```
<script>
  import { inertia, page } from '@inertiajs/inertia-svelte'
  import { route } from '@/utils'
  import Icon from '@/Shared/Icon.svelte'

  export let icon
  export let link
  export let text

  // without looking to $page.url changing, isActive does not update when clicking on sidebar links !
  $: isActive = $page.url && route().current(link + '*')
</script>

<div class="mb-4">
  <a use:inertia href={route(link)} class="flex items-center group py-3">
    <Icon name={icon} class="w-4 h-4 mr-2 {isActive ? 'fill-white' : 'fill-indigo-400 group-hover:fill-white'}" />
    <div class={isActive ? 'text-white' : 'text-indigo-300 group-hover:text-white'}>{text}</div>
  </a>
</div>
```

The "trick" was to listen on $page.url changes (so it depends on a reactive property), otherwise isActive would never change.

PS: I'm new to Svelte. If @reinink or @pedroborges have a different opinion, feel free to correct me or provide another view on this.

**Comment by reinink** [comment]
I've fixed this. Now that the `$page` object includes the url (`$page.url`), we can use this to set active states. See here:

https://github.com/inertiajs/pingcrm-svelte/blob/7003373d02c115f77f9b6adbe1c37ef2993fe1f3/resources/js/Shared/MainMenu.svelte#L6-L8

Much nicer. 👍
