### ISSUE TITLE
user images

### ISSUE THREAD

**Issue by michapixel** [inertiajs/pingcrm-svelte#5]
i can see user images are uploaded but i'm wondering if you missed out to document how to link the storage properly, so user images don't getr publically available. 
if this isn't possible the link to img/user/... still is dead, since the storage isn't linked.

**Comment by reinink** [comment]
Hmm, so the images route was broken in this demo app. I've fixed that: b41d2bd56958608fd583bf92c24d3f1106737117

As for how to manage images with Glide, I'd recommend bringing that up with the maintainers of that package: https://github.com/thephpleague/glide 👍
